on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v2
        with:
          application_id: ${{ secrets.APPLICATION_ID }}
          application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}

      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: go
          package-name: release-please-action
          token: ${{ steps.get_workflow_token.outputs.token }}
          changelog-types: '[{"type":"build","section":"Builds","hidden":false},{"type":"chore","section":"Maintenance","hidden":false},{"type":"ci","section":"Continuous Integration","hidden":false},{"type":"docs","section":"Documentation","hidden":false},{"type":"feat","section":"Features","hidden":false},{"type":"fix","section":"Bug Fixes","hidden":false},{"type":"perf","section":"Performance","hidden":false},{"type":"refactor","section":"Refactoring/Restructuring","hidden":false},{"type":"revert","section":"Revert","hidden":false},{"type":"style","section":"Style","hidden":false},{"type":"test","section":"Testing","hidden":false}]'
